sudo: required
dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
    - depends/built
    - depends/work
    - depends/sdk-sources
    - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j4
    - RUN_UNIT_TESTS=false
    - RUN_FUNCTIONAL_TESTS=false
    - RUN_BENCH=false  # Set to true for any one job that has debug enabled, to quickly check bench is not crashing or hitting assertions
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=1000M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - DOCKER_NAME_TAG=ubuntu:18.04
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - DOCKER_PACKAGES="zip build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"
  matrix:
# ARM32
      - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" BITCOIN_CONFIG="--without-gui"
# ARM64
      - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" DEP_OPTS="NO_QT=1" BITCOIN_CONFIG="--without-gui"
# WINDOWS
      - HOST=x86_64-w64-mingw32 HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64" BITCOIN_CONFIG="--enable-reduce-exports"
# LINUX
      - HOST=x86_64-pc-linux-gnu BITCOIN_CONFIG="--with-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
# OSX
      - HOST=x86_64-apple-darwin16 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools" OSX_SDK=10.11 BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror"
before_install:
  - set -o errexit; source .travis/test_03_before_install.sh
install:
  - set -o errexit; source .travis/test_04_install.sh
before_script:
  - set -o errexit; source .travis/test_05_before_script.sh
script:
  - set -o errexit; source .travis/test_06_script.sh
after_script:
    - echo $TRAVIS_COMMIT_RANGE
before_deploy:
    - sudo chown -R travis:travis /home/travis/
    - "cd $TRAVIS_BUILD_DIR"
    - "chmod +x .travis/test_07_deploy.sh"    
    - "./.travis/test_07_deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: NW1CtGj67Ve1sV8D7sKfPuQghpuIArpNOBhLSqOIGV8gusu44Jh526c2Qwr8AVsWcvDQOjNpZV3vz+adqVG1Rx8OlxWZB1BU1x5l97sax+TQQcryLBkfxBwXQ+elSfZmoGsa/GJCvub5f4SJvQDQbF7TaYkF9PeOgc1hFcByk88XgHD/h4QbKR2/e/JQAXZiPjTI2b272Su/Rh7tCihAu9XmsZUSyXVabgaKT+nk9G2P5KUSJeTI7j+fghyK1SxB6/2Qn1kRthN0hBdvPkzZQbnYnD7mc2/mCRYrGQtCR1xroPeRvXrrwM+U+2rq0HHjPbE2DD1Wmslc2q1Jz5mYlxGhYcKQRIpzGCFR1ThMAmVAZq/vEJedpik4LA/gyHABOHD4Le02iZ4uoHnJkrnP/KTZ6HwfPkMLqOG8q0mrq19N+wncIx993xftETZHll9oqtN6+CD9x9NV8xDhe0vaClWArn+TbzfrEBmzuhIR7uGeULqwEIKJJ1FkSA0tNPi9Ks9AmNVIpmne4EbAHOzmBUJabfQVS5JYcVSLPFehaCVCVTf3mJoEg0VZ4r5jnFMyYpdLP0qFO/4xXG1OingGl83jMxtJy51razHjVL+EPiMUjwOIwJ1VUzYBjmAerCQ3JKMjd2AKmJ5M0NhzkUJGCwrdK0UAtz0zh2LjKmHjYeM=
  file_glob: true
  file:
    - out/**/zip/*
  skip_cleanup: true
  on:
    tags: true
