sudo: required
dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
    - depends/built
    - depends/work
    - depends/sdk-sources
    - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j4
    - RUN_UNIT_TESTS=false
    - RUN_FUNCTIONAL_TESTS=false
    - RUN_BENCH=false  # Set to true for any one job that has debug enabled, to quickly check bench is not crashing or hitting assertions
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=1000M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - DOCKER_NAME_TAG=ubuntu:18.04
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - DOCKER_PACKAGES="zip build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"
  matrix:
# ARM32
      - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" BITCOIN_CONFIG="--without-gui"
# ARM64
      - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" DEP_OPTS="NO_QT=1" BITCOIN_CONFIG="--without-gui"
# Win32
      - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="g++-mingw-w64-i686" BITCOIN_CONFIG="--enable-reduce-exports"
# Win64
      - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64" BITCOIN_CONFIG="--enable-reduce-exports"
# LINUX
      - HOST=x86_64-pc-linux-gnu BITCOIN_CONFIG="--with-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
# OSX
      - HOST=x86_64-apple-darwin16 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools" OSX_SDK=10.11 BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror"
before_install:
  - set -o errexit; source .travis/test_03_before_install.sh
install:
  - set -o errexit; source .travis/test_04_install.sh
before_script:
  - set -o errexit; source .travis/test_05_before_script.sh
script:
  - set -o errexit; source .travis/test_06_script.sh
after_script:
    - echo $TRAVIS_COMMIT_RANGE
before_deploy:
    - sudo chown -R travis:travis /home/travis/
    - "cd $TRAVIS_BUILD_DIR"
    - "chmod +x .travis/test_07_deploy.sh"    
    - "./.travis/test_07_deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: GmkgOEuHkC+CtulY1U7qRV4GNMhXI37OYRbwC9FHKo/vGOChlpaBqXGWM+nGhwVIi9Eu0YdLBfSNky8yNzG3uaQL//vIRbJ1fDTpU4t+U/zpZDpG2ofMk2/2DvZqggVOge8DofbRFLeOLyhp0QSmOd71XwNu/dGiP/7MAxJvuDV9H86pVYSJvN9oIkQLSKVg84ZC1FXKDG4VThBBJ2sKVZn5Hl8YCKSw0iBHDJjmttKoen5iFtwoYfqPZZiCrkflnw4ld/jsY/34w5AKMxkJlmQD/MJ0CHDq5/x9k1Nbd19uwbmBjvF4k6GAXVvwI4MPH6GSXJZnc3GCVvywreWza4okykX56h7I9/vphHp/+RxK4wxEhQQarXPmJZQWb/+GUGSYtEj7/GOD9DkFGc7mjF7JwEK/pCPJ8z/y342JhMKoQdvWlFTXg/AjvOnXbXGZLOwm3OBqJtqOW8Z2X0F/GfczF0fe0DFWUawe6IL5yvObkAWtdOX5lrJ7IMM4W9jtFwJrV2nAFXwk5kdHoihGWyqh27wC/HBrynJl4pYeSvEYA2iQI1bUumfs+zj7MYjTptc0/PyLrjKZgvFmIAnIdVAGPEY+hz3TcvDjem7umGCcBi5oZJqmxUFf+4k27UyvlO7nGGpzO4WtMr0X/C3dcKeuQKnQAAgjcEPuZoc88zM=
  file_glob: true
  file:
    - out/**/zip/*
  skip_cleanup: true
  on:
    tags: true
